# Generated by Django 3.2.5 on 2021-07-21 17:06

from django.db import migrations, models
import django.db.models.deletion
import landingpage.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='enter menu item name', max_length=50)),
                ('price', models.IntegerField(help_text='enter the price', validators=[landingpage.validators.price_menu_validator], verbose_name='price(ir)')),
                ('discount', models.IntegerField(blank=True, null=True, verbose_name='takhfifat')),
                ('serving_time_period', models.IntegerField()),
                ('estimated_cooking_time', models.IntegerField()),
                ('image', models.FileField(blank=True, help_text='enter pic', null=True, upload_to='menu_items/images/', verbose_name='menu image ')),
                ('creat_timestamp', models.DateTimeField(auto_now_add=True, null=True, verbose_name='time creat')),
                ('modify_timestamp', models.DateTimeField(auto_now=True, null=True, verbose_name='time edit')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='landingpage.category', verbose_name='category')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=50)),
                ('number', models.IntegerField()),
                ('date_time_stamp', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=50)),
                ('position', models.CharField(max_length=50)),
                ('status', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_price', models.IntegerField()),
                ('final_price', models.IntegerField()),
                ('date_time_stamp', models.DateTimeField()),
                ('order_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='landingpage.order')),
            ],
        ),
        migrations.CreateModel(
            name='OrderMenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('menu_item_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='landingpage.menuitem')),
                ('order_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='landingpage.order')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='table',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='landingpage.table'),
        ),
    ]
